/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.46
 * Generated at: 2021-07-09 02:20:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class LoginAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1623818084522L));
    _jspx_dependants.put("jar:file:/C:/Users/CT030408/Documents/Eclipse/LC/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LC/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi-VN\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css\">\r\n");
      out.write("<title>Đăng nhập</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("#screen {\r\n");
      out.write("	width: 400px;\r\n");
      out.write("	margin: auto;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("	margin-top: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	background-image:\r\n");
      out.write("		url('https://images.pexels.com/photos/1287142/pexels-photo-1287142.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".top10 {\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	'\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 400px) {\r\n");
      out.write("	#screen {\r\n");
      out.write("		width: 100%;\r\n");
      out.write("		margin-top: 0;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"screen\">\r\n");
      out.write("		<div class=\"text-center bg-warning text-white\" style=\"padding: 5px 0;\">\r\n");
      out.write("			<h1>Đăng nhập</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		<form action=\"login-admin\" method=\"post\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("				<div class=\"col-10 top10\"\r\n");
      out.write("					style=\"background-color: red; color: white;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loi }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("				<div class=\"col-10 top10\">\r\n");
      out.write("					<label for=\"taiKhoan\">Tài khoản:</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("				<div class=\"col-10\">\r\n");
      out.write("					<input class=\"form-control\" type=\"password\" name=\"taiKhoan\"\r\n");
      out.write("						id=\"taiKhoan\" required=\"required\" pattern=\"^[a-zA-Z]+$\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("				<div class=\"col-10 top10\">\r\n");
      out.write("					<label for=\"matKhau\">Mật khẩu:</label>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("				<div class=\"col-10\">\r\n");
      out.write("					<input class=\"form-control\" type=\"password\" name=\"matKhau\"\r\n");
      out.write("						required=\"required\" id=\"matKhau\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("				<div class=\"col-10 top10\">\r\n");
      out.write("					<input class=\"btn btn-success btn-block\" type=\"submit\" id=\"dangKy\"\r\n");
      out.write("						value=\"Đăng nhập\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-1\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("		<div class=\"text-center\">\r\n");
      out.write("			<small><a href=\"get-password\">Quên mật khẩu</a></small>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"text-center\" style=\"padding-bottom: 20px;\">\r\n");
      out.write("			<small>Quay lại <a href=\"home\">trang chủ</a></small>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--\r\n");
      out.write("		<footer>\r\n");
      out.write("			<span class=\"text-center footer fixed-bottom bg-secondary\"\r\n");
      out.write("				style=\"height: 25px;\">\r\n");
      out.write("				<p>© 2021 | Thiết kế bởi Nguyễn Hữu Cường</p>\r\n");
      out.write("			</span>\r\n");
      out.write("		</footer>\r\n");
      out.write("		-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
